env:
  es6: true
  node: true
  mocha: true
extends:
  - google
  - eslint:recommended
parser: babel-eslint
parserOptions:
  ecmaVersion: 2018
  sourceType: script
rules:
  array-bracket-spacing:
    - error
    - always
  camelcase: 'off'
  eol-last:
    - error
    - always
  guard-for-in: 'off'
  max-len: 'off'
  no-multiple-empty-lines:
    - error
    - max: 2
      maxBOF: 0
      maxEOF: 1
  no-template-curly-in-string: error
  no-undef: error
  no-useless-concat: error
  object-curly-spacing:
    - error
    - always
  one-var: 'off'
  quotes:
    - error
    - single
    - allowTemplateLiterals: false
  require-jsdoc: 'off'
  semi:
    - error
    - never
  strict:
    - error
    - global
