name: Automatic Updates

on:
  schedule:
    - cron: "0 0 * * *"
  workflow_dispatch:


jobs:
  auto-update:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Use Node.js 12.x
        uses: actions/setup-node@v1
        with:
          node-version: 12.x
          registry-url: 'https://npm.pkg.github.com'

      - name: Update the package
        run: |
          npm run updates
          git update-index --refresh > /dev/null || npm run bump
        env:
          NODE_AUTH_TOKEN: ${{ secrets.PACKAGES_TOKEN }}

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v3
        with:
          # Use the "PACKAGES_TOKEN" as we want the PR checks to run
          token: ${{ secrets.PACKAGES_TOKEN }}
          commit-message: Automatic update of package dependencies
          committer: Team Juit <developers@juit.com>
          title: Automatic update of package dependencies
          team-reviewers: reviewers
          branch: auto-update
