name: Build Pull Request

on:
  pull_request

jobs:
  build-pr:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Use Node.js 12.x
        uses: actions/setup-node@v1
        with:
          node-version: 12.x
          registry-url: 'https://npm.pkg.github.com'

      - name: Build the package
        id: build
        run: |
          npm clean-install
          npm run build
        env:
          NODE_AUTH_TOKEN: ${{ secrets.PACKAGES_TOKEN }}
